# Generated by Django 2.1 on 2018-10-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hack_id', models.IntegerField(verbose_name='Hack')),
                ('round_no', models.IntegerField(verbose_name='Round')),
                ('round_id', models.IntegerField(verbose_name='RID')),
                ('judge_id', models.IntegerField(verbose_name='Judge')),
                ('team_name', models.CharField(max_length=128, verbose_name='Team Name')),
                ('team_id', models.IntegerField(verbose_name='Team Id')),
                ('critera', models.CharField(max_length=256, verbose_name='Criteria Name')),
                ('mark_weight', models.IntegerField(verbose_name='Weight')),
            ],
            options={
                'db_table': 'core_resonses_vw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Criteria Name')),
            ],
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('desc', models.CharField(blank=True, max_length=128, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='JudgeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criteria')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Role Name')),
            ],
        ),
        migrations.CreateModel(
            name='JudgingRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Round')),
                ('criteria', models.ManyToManyField(to='core.Criteria')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hackathon')),
                ('judges', models.ManyToManyField(to='core.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Scale Name')),
            ],
        ),
        migrations.CreateModel(
            name='ScaleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=64, verbose_name='Entry')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Scale')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Team Name')),
                ('participants', models.CharField(blank=True, max_length=512, verbose_name='Participants: comma-separated')),
            ],
        ),
        migrations.AddField(
            model_name='judginground',
            name='teams',
            field=models.ManyToManyField(to='core.Team'),
        ),
        migrations.AddField(
            model_name='judgeresponse',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ScaleEntry'),
        ),
        migrations.AddField(
            model_name='judgeresponse',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.JudgingRound'),
        ),
        migrations.AddField(
            model_name='judgeresponse',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='judge',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.JudgeRole'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Scale'),
        ),
        migrations.AlterUniqueTogether(
            name='scaleentry',
            unique_together={('scale', 'entry')},
        ),
        migrations.AlterUniqueTogether(
            name='judgeresponse',
            unique_together={('round', 'judge', 'team', 'criterion')},
        ),
    ]
