# Generated by Django 2.1 on 2018-10-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181005_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judginground',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='judginground',
            name='teams',
        ),
        migrations.AddField(
            model_name='judge',
            name='hackathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Hackathon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='hackathon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Hackathon'),
            preserve_default=False,
        ),
    ]
