# Generated by Django 2.1 on 2018-11-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181009_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judginground',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Round'),
        ),
    ]
