# Generated by Django 2.1 on 2018-08-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180829_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('desc', models.CharField(blank=True, max_length=128, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='JudgingRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(verbose_name='Round')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criteria')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Team Name')),
                ('participants', models.CharField(max_length=512, verbose_name='Participants: comma-separated')),
            ],
        ),
        migrations.AlterField(
            model_name='judge',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='judge',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='judginground',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Judge'),
        ),
        migrations.AddField(
            model_name='judginground',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ScaleEntry'),
        ),
        migrations.AddField(
            model_name='judginground',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='judges',
            field=models.ManyToManyField(to='core.Judge'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='teams',
            field=models.ManyToManyField(to='core.Team'),
        ),
    ]
