# Generated by Django 2.1 on 2018-11-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181126_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judginground',
            name='criteria',
        ),
        migrations.AddField(
            model_name='criteria',
            name='judging_round',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='core.JudgingRound'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Criteria Name'),
        ),
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together={('name', 'judging_round')},
        ),
    ]
