# Generated by Django 2.1 on 2018-08-31 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180829_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criteria')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ScaleEntry')),
            ],
        ),
        migrations.RenameField(
            model_name='judginground',
            old_name='round',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='judginground',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='judginground',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='judginground',
            name='team',
        ),
        migrations.AddField(
            model_name='judginground',
            name='judges',
            field=models.ManyToManyField(to='core.Judge'),
        ),
        migrations.AddField(
            model_name='judginground',
            name='teams',
            field=models.ManyToManyField(to='core.Team'),
        ),
        migrations.RemoveField(
            model_name='judginground',
            name='criteria',
        ),
        migrations.AddField(
            model_name='judginground',
            name='criteria',
            field=models.ManyToManyField(to='core.Criteria'),
        ),
        migrations.AddField(
            model_name='judgeresponse',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.JudgingRound'),
        ),
        migrations.AddField(
            model_name='judgeresponse',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
