# Generated by Django 2.1 on 2018-08-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180831_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgeresponse',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='judgeresponse',
            name='team',
        ),
    ]
