# Generated by Django 2.1 on 2018-08-31 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180831_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeresponse',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criteria'),
        ),
        migrations.AlterField(
            model_name='judgeresponse',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Judge'),
        ),
        migrations.AlterField(
            model_name='judgeresponse',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ScaleEntry'),
        ),
        migrations.AlterField(
            model_name='judgeresponse',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
