# Generated by Django 2.1 on 2018-08-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180831_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judginground',
            name='number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Round'),
        ),
    ]
