# Generated by Django 2.1 on 2018-09-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180914_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Scale Name'),
        ),
    ]
