# Generated by Django 2.1 on 2018-09-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180914_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Criteria Name'),
        ),
    ]
