# Generated by Django 2.1 on 2018-09-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180914_1431'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scaleentry',
            unique_together={('scale', 'entry')},
        ),
    ]
